apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: argo-redb
spec:
  redisEnterpriseCluster:
    name: argo-cluster
  memorySize: 100MB
  databasePort: 12000
  replication: false
  persistence: "disabled"