apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: argo-cluster
spec:
  nodes: 3
  redisEnterpriseNodeResources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"